export const routes = {
    "page/plugins/typedDocumentNode": "/page/plugins/typedDocumentNode",
    "page/plugins/react-query": "/page/plugins/react-query",
    "page/plugins/stucco": "/page/plugins/stucco",
    "page/plugins/apollo": "/page/plugins/apollo",
    "page/graphql/variables": "/page/graphql/variables",
    "page/graphql/gql": "/page/graphql/gql",
    "page/graphql/interfaces-and-unions": "/page/graphql/interfaces-and-unions",
    "page/graphql/directives": "/page/graphql/directives",
    "page/graphql/aliases": "/page/graphql/aliases",
    "page/state": "/page/state",
    "page/forms": "/page/forms",
    "page/library": "/page/library",
    "page/spec": "/page/spec",
    "page/selector": "/page/selector",
    "page/getting-started": "/page/getting-started",
    "page/esmodules": "/page/esmodules",
    "page/javascript": "/page/javascript",
    "page/custom-fetch": "/page/custom-fetch",
    "index": "/index"
} as const